version: 2
jobs:
  build_py2:
    docker:
      - image: girder/girder_test:latest

    working_directory: /home/circleci/project # as $CIRCLE_WORKING_DIRECTORY

    steps:
      - checkout:
          path: girder

      - restore_cache:
          key: venv-{{ checksum "girder/setup.py" }}-{{ checksum "girder/requirements-dev.txt" }}
      - run:
          name: Create virtualenv (if necessary)
          command: if [ ! -d venv ]; then virtualenv venv; fi
      - run:
          name: Activate virtualenv
          command: echo "source $CIRCLE_WORKING_DIRECTORY/venv/bin/activate" >> $BASH_ENV
      - run:
          name: Upgrade Python toolchain
          command: pip install --upgrade pip setuptools virtualenv
      - run:
          name: Install Codecov client
          command: pip install codecov
      - run:
          name: Install Girder
          command: |
            pip install -e girder[plugins,sftp]
            pip install -e girder/clients/python
            pip install -r girder/requirements-dev.txt
      - save_cache:
          paths: venv
          key: venv-{{ checksum "girder/setup.py" }}-{{ checksum "girder/requirements-dev.txt" }}

      - restore_cache:
          key: npm-{{ checksum "girder/package-lock.json" }}
      - run:
          name: Build Girder web client
          command: girder-install web --all-plugins --dev | cat
          environment:
            - npm_config_cache: /home/circleci/project/npm_cache
      - save_cache:
          paths: npm_cache
          key: npm-{{ checksum "girder/package-lock.json" }}

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - girder
            - venv

  test_py2_server:
    docker:
      - image: girder/girder_test:latest
        environment:
          # Required for CMake
          PYTHON_VERSION: 2.7.14
          TEST_GROUP: python
      - image: mongo:3.4

    working_directory: /home/circleci/project

    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Activate virtualenv
          command: echo "source $CIRCLE_WORKING_DIRECTORY/venv/bin/activate" >> $BASH_ENV

      - run:
          name: Create Girder build directory
          command: mkdir girder_build
      - run:
          name: Run CTest
          command: |
            touch test_failed
            ctest -VV -S "$CIRCLE_WORKING_DIRECTORY/girder/cmake/circle_continuous.cmake"
          environment:
            COVERAGE_EXECUTABLE: /home/circleci/project/venv/bin/coverage
            FLAKE8_EXECUTABLE: /home/circleci/project/venv/bin/flake8
            VIRTUALENV_EXECUTABLE: /home/circleci/project/venv/bin/virtualenv
            PYTHON_EXECUTABLE: /home/circleci/project/venv/bin/python
            JASMINE_TIMEOUT: 15000
            BABEL_ENV: cover
          working_directory: girder_build

  test_py2_web:
    docker:
      - image: girder/girder_test:latest
        environment:
          PYTHON_VERSION: 2.7.14
          TEST_GROUP: browser
      - image: mongo:3.4

    working_directory: /home/circleci/project

    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Activate virtualenv
          command: echo "source $CIRCLE_WORKING_DIRECTORY/venv/bin/activate" >> $BASH_ENV

      - run:
          name: Create Girder build directory
          command: mkdir girder_build
      - run:
          name: Run CTest
          command: |
            touch test_failed
            ctest -VV -S "$CIRCLE_WORKING_DIRECTORY/girder/cmake/circle_continuous.cmake"
          environment:
            COVERAGE_EXECUTABLE: /home/circleci/project/venv/bin/coverage
            FLAKE8_EXECUTABLE: /home/circleci/project/venv/bin/flake8
            VIRTUALENV_EXECUTABLE: /home/circleci/project/venv/bin/virtualenv
            PYTHON_EXECUTABLE: /home/circleci/project/venv/bin/python
            JASMINE_TIMEOUT: 15000
            BABEL_ENV: cover
          working_directory: girder_build

      #- run:
      #    name: Upload coverage
      #    command: codecov --disable search pycov gcov --file $CIRCLE_WORKING_DIRECTORY/girder_build/coverage.xml
      #    working_directory: girder

workflows:
  version: 2
  build_and_test_py2:
    jobs:
      - build_py2
      - test_py2_server:
          requires:
            - build_py2
      - test_py2_web:
          requires:
            - build_py2
